language: java
jdk: oraclejdk8

sudo: required

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker

script:
  - ./gradlew build
  - PRJ_GROUP=$(gradle properties -q | grep "group:" | awk '{print $2}')
  - PRJ_NAME=$(gradle properties -q | grep "name:" | awk '{print $2}')
  - PRJ_VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}')

  - echo "## PROJECT_GROUP - ${PRJ_GROUP}"
  - echo "## PROJECT_NAME - ${PRJ_NAME}"
  - echo "## PROJECT_VERSION - ${PRJ_VERSION}"

  - PRJ_JAR=${PRJ_NAME}-${PRJ_VERSION}.jar
  - docker build -t ${PRJ_GROUP}.${PRJ_NAME}:latest --build-arg JAR_FILE=build/libs/${PRJ_JAR} ./

  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker tag vw.demo.helloworld:latest voyagerwoo/vw.demo.helloworld:latest
  - docker push voyagerwoo/vw.demo.helloworld:latest